version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt
      - pip install pytest  

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 650520005080.dkr.ecr.ap-south-1.amazonaws.com
      - pytest test_app.py

  build:
    commands:
      - echo Building Docker image...
      - docker build -t login-page .

  post_build:
    commands:
      - echo Tagging and pushing Docker image...
      - docker tag login-page:latest 650520005080.dkr.ecr.ap-south-1.amazonaws.com/login-page:latest
      - docker push 650520005080.dkr.ecr.ap-south-1.amazonaws.com/login-page:latest
      - echo Build completed successfully.
