version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - nohup /usr/local/bin/dockerd-entrypoint.sh &  # for docker daemon
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 650520005080.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-ecr-image .
      - docker tag my-ecr-image:latest 650520005080.dkr.ecr.ap-south-1.amazonaws.com/my-ecr-image:latest
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push 650520005080.dkr.ecr.ap-south-1.amazonaws.com/my-ecr-image:latest
      - echo Build completed on `date`

